laravel/app/Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('o-escritorio', 'EscritorioController@index')->name('o-escritorio');
    Route::get('o-escritorio/expertise', 'EscritorioController@expertise')->name('o-escritorio.expertise');
    Route::get('o-escritorio/clientes', 'EscritorioController@clientes')->name('o-escritorio.clientes');
    Route::get('projetos/{projetos_categoria?}', 'PortfolioController@index')->name('projetos');
    Route::get('projetos/{projetos_categoria}/{projetos_slug}', 'PortfolioController@show')->name('projetos.show');
    //Route::get('portfolio/estudos', 'PortfolioController@estudos')->name('portfolio.estudos');
    //Route::get('portfolio/estudos/{estudos_slug}', 'PortfolioController@estudosShow')->name('portfolio.estudos.show');
    Route::get('equipe', 'EquipeController@index')->name('equipe');
    Route::get('blog', 'BlogController@index')->name('blog');
    Route::get('blog/{post_slug}', 'BlogController@show')->name('blog.show');
    Route::get('contato', 'ContatoController@index')->name('contato');
    Route::post('contato', 'ContatoController@post')->name('contato.post');
    Route::post('ouvidoria', 'ContatoController@postOuvidoria')->name('contato.ouvidoria');
    Route::get('politica-de-privacidade', 'PoliticaDePrivacidadeController@index')->name('politica-de-privacidade');
    Route::post('aceite-de-cookies', 'HomeController@postCookies')->name('aceite-de-cookies.post');

    // Localização
    Route::get('lang/{idioma?}', function ($idioma = 'pt') {
        if ($idioma == 'pt' || $idioma == 'en') Session::put('locale', $idioma);
        return redirect()->back();
    })->name('lang');

    // EBOOK
    Route::resource('ebook', 'EbookController', ['only' => ['index', 'show', 'store']]);
    Route::get('ebook/download/{slug}/{email}', 'EbookController@download')->name('ebook.download');

    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function() {
        Route::get('/', 'PainelController@index')->name('painel');

        /* GENERATED ROUTES */
		Route::resource('destaques', 'DestaquesController');
        Route::resource('projetos/categorias', 'ProjetosCategoriasController', ['parameters' => ['categorias' => 'categorias_projetos']]);
        Route::resource('projetos', 'ProjetosController');
        Route::get('projetos/{projetos}/remover-imagem/{id}', 'ProjetosController@removerImagem')->name('projetos.remover-imagem');
        //Route::resource('projetos.fornecedores', 'FornecedoresController');
		//Route::resource('projetos.equipe', 'ProjetosEquipeController', ['parameters' => ['equipe' => 'equipe_projetos']]);
		//Route::resource('estudos', 'EstudosController');
        //Route::get('estudos/{estudos}/remover-imagem/{id}', 'EstudosController@removerImagem')->name('estudos.remover-imagem');
		Route::resource('escritorio', 'EscritorioController', ['only' => ['index', 'update']]);
		Route::resource('expertise', 'ExpertiseController');
		Route::resource('clientes', 'ClientesController');
		Route::resource('depoimentos', 'DepoimentosController');
		Route::resource('equipe', 'EquipeController');
		Route::resource('blog', 'BlogController');
        Route::get('blog/{blog}/remover-imagem/{id}', 'BlogController@removerImagem')->name('blog.remover-imagem');
		Route::resource('configuracoes', 'ConfiguracoesController', ['only' => ['index', 'update']]);

        Route::get('contato/recebidos/{recebidos}/toggle', ['as' => 'painel.contato.recebidos.toggle', 'uses' => 'ContatosRecebidosController@toggle']);
        Route::resource('contato/recebidos', 'ContatosRecebidosController');
        Route::get('contato/ouvidoria/recebidos/{ouvidoria}/toggle', ['as' => 'painel.contato.ouvidoria.toggle', 'uses' => 'OuvidoriaRecebidosController@toggle']);
        Route::resource('contato/ouvidoria', 'OuvidoriaRecebidosController');
        Route::resource('contato', 'ContatoController');
        Route::resource('usuarios', 'UsuariosController');
        Route::resource('politica-de-privacidade', 'PoliticaDePrivacidadeController', ['only' => ['index', 'update']]);
        Route::get('aceite-de-cookies', 'AceiteDeCookiesController@index')->name('painel.aceite-de-cookies');

        // EBOOK
        Route::get('ebook/arquivos', 'EbookController@index')->name('ebook.arquivos.index');
        Route::get('ebook/arquivos/create', 'EbookController@create')->name('ebook.arquivos.create');
        Route::post('ebook/arquivos/create', 'EbookController@store')->name('ebook.arquivos.store');
        Route::get('ebook/arquivos/edit/{arquivo}', 'EbookController@edit')->name('ebook.arquivos.edit');
        Route::post('ebook/arquivos/edit/{arquivo}', 'EbookController@update')->name('ebook.arquivos.update');
        Route::delete('ebook/arquivos/delete/{arquivo}', 'EbookController@destroy')->name('ebook.arquivos.destroy');
        Route::get('ebook/pagina', 'EbookController@indexPagina')->name('ebook.pagina.index');
        Route::post('ebook/pagina/{registro}', 'EbookController@updatePagina')->name('ebook.pagina.update');
        Route::get('ebook/downloads', 'EbookController@downloads')->name('ebook.downloads');
        Route::get('ebook/downloads/export', 'EbookController@export')->name('ebook.downloads.export');

        Route::post('ckeditor-upload', 'PainelController@imageUpload');
        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

        Route::get('generator', 'GeneratorController@index')->name('generator.index');
        Route::post('generator', 'GeneratorController@submit')->name('generator.submit');
    });

    // Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function() {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
    });
});

laravel/app/Http/Controllers/Painel/AceiteDeCookiesController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Models\AceiteDeCookies;

class AceiteDeCookiesController extends Controller
{
    public function index()
    {
        $registros = AceiteDeCookies::orderBy('created_at', 'DESC')->get();

        return view('painel.aceite-de-cookies', compact('registros'));
    }
}

laravel/app/Http/Controllers/Painel/BlogController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\BlogRequest;
use App\Http\Controllers\Controller;

use App\Models\Post;

class BlogController extends Controller
{
    public function index()
    {
        $registros = Post::orderBy('data', 'DESC')->orderBy('id', 'DESC')->paginate(10);

        return view('painel.blog.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.blog.create');
    }

    public function store(BlogRequest $request)
    {
        try {

            $input = $request->all();

            if (isset($input['capa'])) $input['capa'] = Post::upload_capa();

            Post::create($input);

            return redirect()->route('painel.blog.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Post $registro)
    {
        return view('painel.blog.edit', compact('registro'));
    }

    public function update(BlogRequest $request, Post $registro)
    {
        try {

            $input = $request->all();

            if (isset($input['capa'])) $input['capa'] = Post::upload_capa();

            $registro->update($input);

            return redirect()->route('painel.blog.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Post $registro)
    {
        try {

            $registro->delete();

            return redirect()->route('painel.blog.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/ClientesController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ClientesRequest;
use App\Http\Controllers\Controller;

use App\Models\Cliente;

class ClientesController extends Controller
{
    public function index()
    {
        $registros = Cliente::ordenados()->get();

        return view('painel.clientes.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.clientes.create');
    }

    public function store(ClientesRequest $request)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Cliente::upload_imagem();

            Cliente::create($input);

            return redirect()->route('painel.clientes.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Cliente $registro)
    {
        return view('painel.clientes.edit', compact('registro'));
    }

    public function update(ClientesRequest $request, Cliente $registro)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Cliente::upload_imagem();

            $registro->update($input);

            return redirect()->route('painel.clientes.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Cliente $registro)
    {
        try {

            $registro->delete();

            return redirect()->route('painel.clientes.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/ConfiguracoesController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ConfiguracoesRequest;
use App\Http\Controllers\Controller;

use App\Models\Configuracoes;

class ConfiguracoesController extends Controller
{
    public function index()
    {
        $registro = Configuracoes::first();

        return view('painel.configuracoes.edit', compact('registro'));
    }

    public function update(ConfiguracoesRequest $request, Configuracoes $registro)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem_de_compartilhamento'])) $input['imagem_de_compartilhamento'] = Configuracoes::upload_imagem_de_compartilhamento();

            $registro->update($input);

            return redirect()->route('painel.configuracoes.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/ContatoController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ContatoRequest;
use App\Http\Controllers\Controller;

use App\Models\Contato;

class ContatoController extends Controller
{
    public function index()
    {
        $contato = Contato::first();

        return view('painel.contato.index', compact('contato'));
    }

    public function update(ContatoRequest $request, Contato $contato)
    {
        try {

            $input = $request->all();

            $contato->update($input);
            return redirect()->route('painel.contato.index')->with('success', 'Informações alteradas com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar informações: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/ContatosRecebidosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Models\ContatoRecebido;

class ContatosRecebidosController extends Controller
{
    public function index()
    {
        $contatosrecebidos = ContatoRecebido::orderBy('created_at', 'DESC')->get();

        return view('painel.contato.recebidos.index', compact('contatosrecebidos'));
    }

    public function show(ContatoRecebido $contato)
    {
        $contato->update(['lido' => 1]);

        return view('painel.contato.recebidos.show', compact('contato'));
    }

    public function destroy(ContatoRecebido $contato)
    {
        try {

            $contato->delete();
            return redirect()->route('painel.contato.recebidos.index')->with('success', 'Mensagem excluída com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir mensagem: '.$e->getMessage()]);

        }
    }

    public function toggle(ContatoRecebido $contato, Request $request)
    {
        try {

            $contato->update([
                'lido' => !$contato->lido
            ]);

            return redirect()->route('painel.contato.recebidos.index')->with('success', 'Mensagem alterada com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar mensagem: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/DepoimentosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\DepoimentosRequest;
use App\Http\Controllers\Controller;

use App\Models\Depoimento;

class DepoimentosController extends Controller
{
    public function index()
    {
        $registros = Depoimento::ordenados()->get();

        return view('painel.depoimentos.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.depoimentos.create');
    }

    public function store(DepoimentosRequest $request)
    {
        try {

            $input = $request->all();

            Depoimento::create($input);

            return redirect()->route('painel.depoimentos.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Depoimento $registro)
    {
        return view('painel.depoimentos.edit', compact('registro'));
    }

    public function update(DepoimentosRequest $request, Depoimento $registro)
    {
        try {

            $input = $request->all();

            $registro->update($input);

            return redirect()->route('painel.depoimentos.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Depoimento $registro)
    {
        try {

            $registro->delete();

            return redirect()->route('painel.depoimentos.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/EquipeController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\EquipeRequest;
use App\Http\Controllers\Controller;

use App\Models\Equipe;

class EquipeController extends Controller
{
    public function index()
    {
        $registros = Equipe::ordenados()->get();

        return view('painel.equipe.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.equipe.create');
    }

    public function store(EquipeRequest $request)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Equipe::upload_imagem();

            Equipe::create($input);

            return redirect()->route('painel.equipe.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Equipe $registro)
    {
        return view('painel.equipe.edit', compact('registro'));
    }

    public function update(EquipeRequest $request, Equipe $registro)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Equipe::upload_imagem();

            $registro->update($input);

            return redirect()->route('painel.equipe.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Equipe $registro)
    {
        try {

            $registro->delete();

            return redirect()->route('painel.equipe.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/resources/views/painel/common/flash.blade.php
@if(session('success'))
   <div class="alert alert-block alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {!! session('success') !!}
    </div>
@endif

@if($errors->any())
    <div class="alert alert-block alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        @foreach($errors->all() as $error)
        {!! $error !!}<br>
        @endforeach
    </div>
@endif

laravel/resources/views/painel/common/header.blade.php
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url('/') }}">{{ $config->nome_do_site }}</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
            @include('painel.common.nav')

            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown @if(str_is('painel.usuarios*', Route::currentRouteName()) || str_is('painel.configuracoes*', Route::currentRouteName()) || str_is('painel.politica-de-privacidade*', Route::currentRouteName()) || str_is('painel.aceite-de-cookies*', Route::currentRouteName())) active @endif">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <span class="glyphicon glyphicon-cog small" style="margin-right:3px"></span>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li @if(str_is('painel.politica-de-privacidade*', Route::currentRouteName())) class="active" @endif>
                            <a href="{{ route('painel.politica-de-privacidade.index') }}">Política de Privacidade</a>
                        </li>
                        <li @if(str_is('painel.aceite-de-cookies*', Route::currentRouteName())) class="active" @endif>
                            <a href="{{ route('painel.aceite-de-cookies') }}">Relatório de Cookies</a>
                        </li>
                        <li @if(str_is('painel.configuracoes*', Route::currentRouteName())) class="active" @endif>
                            <a href="{{ route('painel.configuracoes.index') }}">Configurações</a>
                        </li>
                        <li @if(str_is('painel.usuarios*', Route::currentRouteName())) class="active" @endif>
                            <a href="{{ route('painel.usuarios.index') }}">Usuários</a>
                        </li>
                        <li><a href="{{ route('logout') }}">Logout</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

laravel/resources/views/painel/common/nav.blade.php
<ul class="nav navbar-nav">
	<li @if(str_is('painel.destaques*', Route::currentRouteName())) class="active" @endif>
		<a href="{{ route('painel.destaques.index') }}">Destaques</a>
	</li>
    <li @if(str_is('painel.escritorio*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.escritorio.index') }}">Escritório</a>
    </li>
	<li @if(str_is('painel.projetos*', Route::currentRouteName())) class="active" @endif>
		<a href="{{ route('painel.projetos.index') }}">Projetos</a>
	</li>
	{{--<li @if(str_is('painel.estudos*', Route::currentRouteName())) class="active" @endif>
		<a href="{{ route('painel.estudos.index') }}">Estudos</a>
	</li>--}}
	<li @if(str_is('painel.expertise*', Route::currentRouteName())) class="active" @endif>
		<a href="{{ route('painel.expertise.index') }}">Expertise</a>
	</li>
	<li @if(str_is('painel.clientes*', Route::currentRouteName())) class="active" @endif>
		<a href="{{ route('painel.clientes.index') }}">Clientes</a>
	</li>
	<li @if(str_is('painel.depoimentos*', Route::currentRouteName())) class="active" @endif>
		<a href="{{ route('painel.depoimentos.index') }}">Depoimentos</a>
	</li>
	<li @if(str_is('painel.equipe*', Route::currentRouteName())) class="active" @endif>
		<a href="{{ route('painel.equipe.index') }}">Equipe</a>
	</li>
	<li @if(str_is('painel.blog*', Route::currentRouteName())) class="active" @endif>
		<a href="{{ route('painel.blog.index') }}">Blog</a>
	</li>
    <li class="dropdown @if(str_is('painel.contato*', Route::currentRouteName())) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Contato
            @if(($contatosNaoLidos + $ouvidoriaNaoLidos) >= 1)
            <span class="label label-success" style="margin-left:3px;">{{ $contatosNaoLidos + $ouvidoriaNaoLidos }}</span>
            @endif
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li @if(str_is('painel.contato.index', Route::currentRouteName())) class="active" @endif><a href="{{ route('painel.contato.index') }}">Informações de Contato</a></li>
            <li @if(str_is('painel.contato.recebidos.*', Route::currentRouteName())) class="active" @endif><a href="{{ route('painel.contato.recebidos.index') }}">
                Contatos Recebidos
                @if($contatosNaoLidos >= 1)
                <span class="label label-success" style="margin-left:3px;">{{ $contatosNaoLidos }}</span>
                @endif
            </a></li>
            <li @if(str_is('painel.contato.ouvidoria.*', Route::currentRouteName())) class="active" @endif><a href="{{ route('painel.contato.ouvidoria.index') }}">
                Ouvidoria
                @if($ouvidoriaNaoLidos >= 1)
                <span class="label label-success" style="margin-left:3px;">{{ $ouvidoriaNaoLidos }}</span>
                @endif
            </a></li>
        </ul>
    </li>
    <li class="dropdown @if(str_is('painel.contato*', Route::currentRouteName())) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            E-book
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li @if(str_is('painel.ebook.pagina.index', Route::currentRouteName())) class="active" @endif><a href="{{ route('ebook.pagina.index') }}">Pagina</a></li>
            <li @if(str_is('painel.ebook.arquivos.*', Route::currentRouteName())) class="active" @endif><a href="{{ route('ebook.arquivos.index') }}">Arquivos</a></li>
            <li @if(str_is('painel.ebook.downloads.*', Route::currentRouteName())) class="active" @endif><a href="{{ route('ebook.downloads') }}">Downloads</a></li>
        </ul>
    </li>
</ul>

laravel/resources/views/painel/common/template.blade.php
<!doctype html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <base href="{{ url('/') }}">

    <title>{{ $config->nome_do_site }} - Painel Administrativo</title>

    {!! Tools::loadCss('vendor/bootswatch-dist/css/bootstrap.min.css') !!}
    {!! Tools::loadCss('css/vendor.painel.css') !!}
    {!! Tools::loadCss('css/painel.css') !!}
</head>
<body>
    @include('painel.common.header')

    <div class="container" style="padding-bottom:30px;">
        @yield('content')
    </div>

    {!! Tools::loadJquery() !!}
    {!! Tools::loadJs('vendor/ckeditor/ckeditor.js') !!}
    {!! Tools::loadJs('js/vendor.painel.js') !!}
    {!! Tools::loadJs('js/painel.js') !!}
</body>
</html>