laravel/app/Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('o-escritorio', 'EscritorioController@index')->name('o-escritorio');
    Route::get('o-escritorio/expertise', 'EscritorioController@expertise')->name('o-escritorio.expertise');
    Route::get('o-escritorio/clientes', 'EscritorioController@clientes')->name('o-escritorio.clientes');
    Route::get('projetos/{projetos_categoria?}', 'PortfolioController@index')->name('projetos');
    Route::get('projetos/{projetos_categoria}/{projetos_slug}', 'PortfolioController@show')->name('projetos.show');
    //Route::get('portfolio/estudos', 'PortfolioController@estudos')->name('portfolio.estudos');
    //Route::get('portfolio/estudos/{estudos_slug}', 'PortfolioController@estudosShow')->name('portfolio.estudos.show');
    Route::get('equipe', 'EquipeController@index')->name('equipe');
    Route::get('blog', 'BlogController@index')->name('blog');
    Route::get('blog/{post_slug}', 'BlogController@show')->name('blog.show');
    Route::get('contato', 'ContatoController@index')->name('contato');
    Route::post('contato', 'ContatoController@post')->name('contato.post');
    Route::post('ouvidoria', 'ContatoController@postOuvidoria')->name('contato.ouvidoria');
    Route::get('politica-de-privacidade', 'PoliticaDePrivacidadeController@index')->name('politica-de-privacidade');
    Route::post('aceite-de-cookies', 'HomeController@postCookies')->name('aceite-de-cookies.post');

    // Localização
    Route::get('lang/{idioma?}', function ($idioma = 'pt') {
        if ($idioma == 'pt' || $idioma == 'en') Session::put('locale', $idioma);
        return redirect()->back();
    })->name('lang');

    // EBOOK
    Route::resource('ebook', 'EbookController', ['only' => ['index', 'show', 'store']]);
    Route::get('ebook/download/{slug}/{email}', 'EbookController@download')->name('ebook.download');

    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function() {
        Route::get('/', 'PainelController@index')->name('painel');

        /* GENERATED ROUTES */
		Route::resource('destaques', 'DestaquesController');
        Route::resource('projetos/categorias', 'ProjetosCategoriasController', ['parameters' => ['categorias' => 'categorias_projetos']]);
        Route::resource('projetos', 'ProjetosController');
        Route::get('projetos/{projetos}/remover-imagem/{id}', 'ProjetosController@removerImagem')->name('projetos.remover-imagem');
        //Route::resource('projetos.fornecedores', 'FornecedoresController');
		//Route::resource('projetos.equipe', 'ProjetosEquipeController', ['parameters' => ['equipe' => 'equipe_projetos']]);
		//Route::resource('estudos', 'EstudosController');
        //Route::get('estudos/{estudos}/remover-imagem/{id}', 'EstudosController@removerImagem')->name('estudos.remover-imagem');
		Route::resource('escritorio', 'EscritorioController', ['only' => ['index', 'update']]);
		Route::resource('expertise', 'ExpertiseController');
		Route::resource('clientes', 'ClientesController');
		Route::resource('depoimentos', 'DepoimentosController');
		Route::resource('equipe', 'EquipeController');
		Route::resource('blog', 'BlogController');
        Route::get('blog/{blog}/remover-imagem/{id}', 'BlogController@removerImagem')->name('blog.remover-imagem');
		Route::resource('configuracoes', 'ConfiguracoesController', ['only' => ['index', 'update']]);

        Route::get('contato/recebidos/{recebidos}/toggle', ['as' => 'painel.contato.recebidos.toggle', 'uses' => 'ContatosRecebidosController@toggle']);
        Route::resource('contato/recebidos', 'ContatosRecebidosController');
        Route::get('contato/ouvidoria/recebidos/{ouvidoria}/toggle', ['as' => 'painel.contato.ouvidoria.toggle', 'uses' => 'OuvidoriaRecebidosController@toggle']);
        Route::resource('contato/ouvidoria', 'OuvidoriaRecebidosController');
        Route::resource('contato', 'ContatoController');
        Route::resource('usuarios', 'UsuariosController');
        Route::resource('politica-de-privacidade', 'PoliticaDePrivacidadeController', ['only' => ['index', 'update']]);
        Route::get('aceite-de-cookies', 'AceiteDeCookiesController@index')->name('painel.aceite-de-cookies');

        // EBOOK
        Route::get('ebook/arquivos', 'EbookController@index')->name('ebook.arquivos.index');
        Route::get('ebook/arquivos/create', 'EbookController@create')->name('ebook.arquivos.create');
        Route::post('ebook/arquivos/create', 'EbookController@store')->name('ebook.arquivos.store');
        Route::get('ebook/arquivos/edit/{arquivo}', 'EbookController@edit')->name('ebook.arquivos.edit');
        Route::post('ebook/arquivos/edit/{arquivo}', 'EbookController@update')->name('ebook.arquivos.update');
        Route::delete('ebook/arquivos/delete/{arquivo}', 'EbookController@destroy')->name('ebook.arquivos.destroy');
        Route::get('ebook/pagina', 'EbookController@indexPagina')->name('ebook.pagina.index');
        Route::post('ebook/pagina/{registro}', 'EbookController@updatePagina')->name('ebook.pagina.update');
        Route::get('ebook/downloads', 'EbookController@downloads')->name('ebook.downloads');
        Route::get('ebook/downloads/export', 'EbookController@export')->name('ebook.downloads.export');

        Route::post('ckeditor-upload', 'PainelController@imageUpload');
        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

        Route::get('generator', 'GeneratorController@index')->name('generator.index');
        Route::post('generator', 'GeneratorController@submit')->name('generator.submit');
    });

    // Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function() {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
    });
});

laravel/app/Models/Contato.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Contato extends Model
{
    protected $table = 'contato';

    protected $guarded = ['id'];
}

laravel/app/Models/ContatoRecebido.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class ContatoRecebido extends Model
{
    protected $table = 'contatos_recebidos';

    protected $guarded = ['id'];

    public function getCreatedAtAttribute($date)
    {
        return \Carbon\Carbon::createFromFormat('Y-m-d H:i:s', $date)->format('d/m/Y');
    }

    public function getCreatedAtOrderAttribute()
    {
        return \Carbon\Carbon::createFromFormat('d/m/Y', $this->created_at)->format('Y-m-d');
    }

    public function scopeNaoLidos($query)
    {
        return $query->where('lido', '!=', 1);
    }

    public function countNaoLidos()
    {
        return $this->naoLidos()->count();
    }
}

laravel/app/Http/Controllers/ContatoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Models\Contato;
use App\Http\Requests\ContatosRecebidosRequest;
use App\Http\Requests\OuvidoriaRecebidosRequest;
use App\Models\ContatoRecebido;
use App\Models\OuvidoriaRecebido;

class ContatoController extends Controller
{
    public function index()
    {
        $contato = Contato::first();

        return view('frontend.contato', compact('contato'));
    }

    public function post(ContatosRecebidosRequest $request, ContatoRecebido $contatoRecebido)
    {
        $input = $request->all();

        $contatoRecebido->create($input);

        $contato = Contato::first();

        if (isset($contato->email)) {
            \Mail::send('emails.contato', $input, function ($message) use ($request, $contato) {
                $message->to($contato->email, 'LPA')
                        ->subject('[CONTATO] LPA')
                        ->replyTo($request->get('email'), $request->get('nome'));
            });
        }

        $response = [
            'status'  => 'success',
            'message' => trans('frontend.contato.sucesso')
        ];

        return response()->json($response);
    }

    public function postOuvidoria(OuvidoriaRecebidosRequest $request, OuvidoriaRecebido $contatoRecebido)
    {
        $input = $request->all();

        $contatoRecebido->create($input);

        $contato = Contato::first();

        if (isset($contato->email) && $input['email']) {
            \Mail::send('emails.ouvidoria', $input, function ($message) use ($request, $contato) {
                $message->to($contato->email, 'LPA')
                        ->subject('[OUVIDORIA] LPA')
                        ->replyTo($request->get('email'), $request->get('nome'));
            });
        }

        $response = [
            'status'  => 'success',
            'message' => trans('frontend.contato.sucesso')
        ];

        return response()->json($response);
    }
}

laravel/app/Http/Controllers/Painel/ContatoController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ContatoRequest;
use App\Http\Controllers\Controller;

use App\Models\Contato;

class ContatoController extends Controller
{
    public function index()
    {
        $contato = Contato::first();

        return view('painel.contato.index', compact('contato'));
    }

    public function update(ContatoRequest $request, Contato $contato)
    {
        try {

            $input = $request->all();

            $contato->update($input);
            return redirect()->route('painel.contato.index')->with('success', 'Informações alteradas com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar informações: '.$e->getMessage()]);

        }
    }
}

laravel/resources/views/painel/contato/ouvidoria/index.blade.php
@extends('painel.common.template')

@section('content')

    @include('painel.common.flash')

    <legend>
        <h2>Ouvidoria</h2>
    </legend>

    @if(!count($contatosrecebidos))
    <div class="alert alert-warning" role="alert">Nenhuma mensagem recebida.</div>
    @else
    <table class="table table-striped table-bordered table-hover data-table">
        <thead>
            <tr>
                <th>Data</th>
                <th>Nome</th>
                <th>E-mail</th>
                <th class="no-filter"><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
        @foreach ($contatosrecebidos as $contato)

            <tr class="tr-row @if(!$contato->lido) warning @endif">
                <td data-order="{{ $contato->created_at_order }}">{{ $contato->created_at }}</td>
                <td>{{ $contato->nome ?: 'Anônimo' }}</td>
                <td>
                    @if($contato->email)
                    <button class="btn btn-info btn-sm clipboard" data-clipboard-text="{{ $contato->email }}" style="margin-right:5px;border:0;transition:background .3s">
                        <span class="glyphicon glyphicon-copy"></span>
                    </button>
                    {{ $contato->email }}
                    @else
                    Anônimo
                    @endif
                </td>
                <td class="crud-actions">
                    {!! Form::open([
                        'route'  => ['painel.contato.ouvidoria.destroy', $contato->id],
                        'method' => 'delete'
                    ]) !!}

                    <div class="btn-group btn-group-sm">
                        <a href="{{ route('painel.contato.ouvidoria.show', $contato->id ) }}" class="btn btn-primary btn-sm pull-left">
                            <span class="glyphicon glyphicon-align-left" style="margin-right:10px;"></span>Ler mensagem
                        </a>

                        <button type="submit" class="btn btn-danger btn-sm btn-delete"><span class="glyphicon glyphicon-remove" style="margin-right:10px;"></span>Excluir</button>

                        <a href="{{ route('painel.contato.ouvidoria.toggle', $contato->id) }}" class="btn btn-sm pull-left {{ ($contato->lido ? 'btn-warning' : 'btn-success') }}">
                            <span class="glyphicon small {{ ($contato->lido ? 'glyphicon-repeat' : 'glyphicon-ok') }}"></span>
                        </a>
                    </div>

                    {!! Form::close() !!}
                </td>
            </tr>

        @endforeach
        </tbody>
    </table>
    @endif

@stop

laravel/resources/views/painel/contato/ouvidoria/show.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2>Contatos Recebidos</h2>
    </legend>

    <div class="form-group">
        <label>Data</label>
        <div class="well">{{ $contato->created_at }}</div>
    </div>

    <div class="form-group">
        <label>Nome</label>
        <div class="well">{{ $contato->nome ?: 'Anônimo' }}</div>
    </div>

    <div class="form-group">
        <label>E-mail</label>
        <div class="well">
            @if($contato->email)
            <button class="btn btn-info btn-sm clipboard" data-clipboard-text="{{ $contato->email }}" style="margin-right:5px;border:0;transition:background .3s">
                <span class="glyphicon glyphicon-copy"></span>
            </button>
            {{ $contato->email }}
            @else
            Anônimo
            @endif
        </div>
    </div>

    <div class="form-group">
        <label>Mensagem</label>
        <div class="well">{{ $contato->mensagem }}</div>
    </div>

    <a href="{{ route('painel.contato.ouvidoria.index') }}" class="btn btn-default btn-voltar">Voltar</a>

@stop